# Generated by Django 4.2.2 on 2023-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_token',
            field=models.TextField(null=True),
        ),
    ]
