# Generated by Django 4.2.2 on 2023-07-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_customuser_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_conditions',
            field=models.BooleanField(null=True),
        ),
    ]
